version: "3.7"

services:
    zipkin:
        image: openzipkin/zipkin-slim
        ports:
            - '9411:9411'

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"
